### ISSUE TITLE
VCSEC 4.9.0+

### ISSUE THREAD

**Issue by LexNastin** [trifinite/vcsec-archive#1]
Hey, do you have any plans on further extracting the VCSEC? Any help needed? What do you mean by the app being more obfuscated in the presentation? To which extent? Thanks!

**Comment by mherfurt** [comment]
Hey Lex!
It would be great if you could help extracting VCSEC from the app!

**Comment by Whirlwind** [comment]
Hey, I want to help this project, extract the VCSEC, but I don't know how to do it. Is there somebody teach mine?

**Comment by LexNastin** [comment]
First of all, thanks for offering your help. Second of all, I have a script that does this automatically in 5 minutes so help is definitely not needed, and finally, Tesla has released all the protocol files including VCSEC and some others in their vehicle-control repo. Thanks for offering though!

**Comment by Whirlwind** [comment]
> Tesla has released all the protocol files including VCSEC and some others in their vehicle-control repo.

Sorry, I can not find the repo. Could you tell me the url?

**Comment by LexNastin** [comment]
https://github.com/teslamotors/vehicle-command

**Comment by Whirlwind** [comment]
Thanks very much. By the way, I still want to known that how to extract the VCSEC by your script from the tesla.apk. :)

**Comment by LexNastin** [comment]
Not sure if it will work for you, but here you go: https://github.com/ArchGryphon9362/ArchsLazinessScripts/tree/main/vcsec_extractor

It’s for linux/macos though, haven’t tried on windows through cygwin nor wsl.

**Comment by Whirlwind** [comment]
> Not sure if it will work for you, but here you go: https://github.com/ArchGryphon9362/ArchsLazinessScripts/tree/main/vcsec_extractor
> 
> It’s for linux/macos though, haven’t tried on windows through cygwin nor wsl.

The repo is removed. :(
It is a very good project and I use it extract the protobuf file from tesla.apk. But It not works for tesla 4.29.0.
Could you tell me what can I do to get the protobuf?
